### PR TITLE
Fix -x test file permissions

### PR DESCRIPTION
**Pull request by mvorisek**
also rename non-html test/fixture files to `.txt`

### CODE REVIEW

**Comment by mvorisek** [comment]
Also, not sure if you noticed:
```
PHPUnit 10.5.20 by Sebastian Bergmann and contributors.
Runtime:       PHP 8.3.7 with PCOV 1.0.11
Configuration: /home/runner/work/sql-formatter/sql-formatter/phpunit.xml.dist
R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R  63 / 243 ( 25%)
.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R. 126 / 243 ( 51%)
R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R 189 / 243 ( 77%)
.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R.R          243 / 243 (100%)
Time: 00:00.473, Memory: 26.00 MB
There were 122 risky tests:
1) Doctrine\SqlFormatter\Tests\SqlFormatterTest::testFormatHighlight with data set #0 ('SELECT customer_id, customer_... DESC;', '<pre style="color: black; bac...</pre>')
This test executed code that is not listed as code to be covered or used:
- Doctrine\SqlFormatter\Cursor
- Doctrine\SqlFormatter\HtmlHighlighter
- Doctrine\SqlFormatter\Token
- Doctrine\SqlFormatter\Tokenizer
/home/runner/work/sql-formatter/sql-formatter/tests/SqlFormatterTest.php:40
```

I am not gonna fix these, but it would be good to look at them as it seems not desired CI behaviour to me.

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
> This test executed code that is not listed as code to be covered or used

I think we should stop annotating the expected coverage, tbh.

**Comment by mvorisek** [comment]
Remove these https://github.com/doctrine/sql-formatter/blob/1.4.0/phpunit.xml.dist#L10-L11 lines?

In DBAL there are no such lines - https://github.com/doctrine/dbal/blob/4.0.2/phpunit.xml.dist

**Comment by derrabus** [comment]
> Remove these https://github.com/doctrine/sql-formatter/blob/1.4.0/phpunit.xml.dist#L10-L11 lines?

Yes, and the corresponding attributes from the test classes.

**Pull request merged**
