### PR TITLE
Parse "NOW()" like any other function

### PR DESCRIPTION
**Pull request by mvorisek**
`now()` should not be parsed as one token, especially as it can be `now( )` or `now(6)`.

It should be parsed/formatted like any other (3 letter) function like `xyz()`.

### CODE REVIEW

**Comment by mvorisek** [comment]
@derrabus can I please have your review here?

**Comment by derrabus** [comment]
Do we know why `NOW()` gets the special treatment currently that you're attempting to revert?

**Comment by mvorisek** [comment]
Based on git history this was introduced in https://github.com/jdorn/sql-formatter/commit/e1aa999f64b222bdd990be6408f832c616ac57cf and the PR title refers to https://github.com/jdorn/sql-formatter/pull/47. I guess this was added for MySQL to format `NOW()` more like a value (single token), but as discussed above, this is not consistent with `NOW( )` or `NOW(6)`, or different function like `COW()`. So with this said, I am not aware of any specific purpose/past discussion outside this so it seems as a pure inconsistency for me.

**Review by derrabus — APPROVED** [review]
Makes sense to me.

**Comment by derrabus** [comment]
Can you please rebase? Our CI has changed significantly in 1.4.

**Comment by mvorisek** [comment]
Rebased but it seems you have to approve the CI again. Can you approve it for me for all (future) pushes to this repo/org?

**Comment by derrabus** [comment]
> Can you approve it for me for all (future) pushes to this repo/org?

No. You need to have contributed successfully to this repo at least once. Then, GitHub won't ask for workflow approvals anymore.

**Review by derrabus — APPROVED** [review]

**Comment by derrabus** [comment]
… which should be the case now. Try to rebase your other PRs and they should trigger the CI instantly.

**Comment by mvorisek** [comment]
Thank you!

**Pull request merged**
