### PR TITLE
Add support for common table expressions and window functions

### LINKED ISSUE #37: Add support for the WINDOW keyword
See https://github.com/jdorn/sql-formatter/issues/71

### PR DESCRIPTION
**Pull request by ndm2**
Now to the main show, this adds support for common table expressions and window functions.

I would have liked to add additional nesting on new lines for the `FILTER()` and `OVER()` clauses, eg:

```sql
GROUP_CONCAT(b, '.')
  FILTER (
    WHERE
      c != 'two'
  )
  OVER (
    ORDER BY
      a
  )
  AS filtered,
```

however without a larger rewrite of the formatter, all I could come up with was pretty hack-ish, and way too much tied to this specific syntax, so for now it would still be a bit squished.

Resolves #37

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
@derrabus @goetas please review

**Comment by derrabus** [comment]
I'm not sure I'm the right person to review code on this repo. 😓

**Comment by greg0ire** [comment]
No worries! Let's merge then!

**Comment by ndm2** [comment]
@greg0ire Any chance that we'll see a new release somewhat soon-ish?

**Comment by greg0ire** [comment]
Yes, sorry! https://github.com/doctrine/sql-formatter/releases/tag/1.1.3

**Comment by ndm2** [comment]
Thanks for the swift response, no need to apologize :)

**Pull request merged**
