### PR TITLE
Fix unopened END indent opened by BEGIN

### PR DESCRIPTION
**Pull request by mvorisek**
needs #110 (into 1.4.x as bugfix) and #114 (fix merge conflicts)

fix #101 (`END` indentation when used with `BEGIN`)

grammars:
- https://learn.microsoft.com/en-us/sql/t-sql/language-elements/begin-end-transact-sql?view=sql-server-ver16
- https://learn.microsoft.com/en-us/sql/t-sql/language-elements/try-catch-transact-sql?view=sql-server-ver16

### CODE REVIEW

**Comment by mvorisek** [comment]
@greg0ire here is the PR fixing 1.5.x.

**Comment by greg0ire** [comment]
@mvorisek please run `phpcbf`

**Comment by mvorisek** [comment]
done

**Comment by greg0ire** [comment]
Thanks @mvorisek !

**Pull request merged**
