### PR TITLE
Dedup indent level decrease code

### PR DESCRIPTION
**Pull request by mvorisek**
as requested in https://github.com/doctrine/sql-formatter/pull/110#discussion_r1606259113

### CODE REVIEW

**Comment by mvorisek** [comment]
@greg0ire and also this small refactoring into 1.5.x, please.

**Comment by greg0ire** [comment]
> Fix slow array_unshift/shift, appending is faster

Have you been able to measure a meaningful difference in our case?

**Comment by mvorisek** [comment]
Now I did - https://3v4l.org/eFdHL/rfc#vgit.master_jit - array shift/unshift is simply very costly and should never be used if appending is an option. Even with a small element count.

**Review by greg0ire — APPROVED** [review]
Looking at the execution time of the test suite, it seems faster as well.
[Before](https://github.com/doctrine/sql-formatter/actions/runs/9172379694/)
[After](https://github.com/doctrine/sql-formatter/actions/runs/9198551315)

It's not exactly scientific, but since your changes don't make the code harder to read, I'd say let's go with that.

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @SenseException !

**Pull request merged**
