### PR TITLE
Force uppercase SQL keywords

### PR DESCRIPTION
**Pull request by rinu**
I don't see any benefit to anyone ever having lowercase keywords.

Not all reserved words are detected correctly in this project. A simple regex is simple but it lacks context. But so what, if it's a field name, put ticks around it.

Closes #73

### CODE REVIEW

**Comment by derrabus** [comment]
How does this PR relate to #73?

**Comment by rinu** [comment]
> How does this PR relate to #73?

This is much simpler. No options to argue about. If accepted, it would replace #73.

**Review by greg0ire — APPROVED** [review]
From #73:

> This adds a new optional third parameter to the format method, $forceUppercase which defaults to false to maintain backwards compatibility.

I don't think we should consider changing case as breaking compatibility.

**Comment by rinu** [comment]
I don't see the benefit of keeping compatibility in this case.

**Comment by greg0ire** [comment]
I'm not saying we should not keep compatibility, I'm saying that we should consider that we are keeping it: a change in case should IMO be considered compatible.

**Review by SenseException — APPROVED** [review]
> a change in case should IMO be considered compatible.

I haven't worked with a SQL dialect yet that was case sensitive.

**Comment by greg0ire** [comment]
Thanks @rinu !

**Pull request merged**
