### PR TITLE
Remove trailing whitespace

### LINKED ISSUE #29: Remove trailing spaces from generated SQL
I observed it after saving a test file (I configured my editor to remove trailing spaces). Also, see https://github.com/doctrine/migrations/pull/924 cc @julienfalque

### PR DESCRIPTION
**Pull request by greg0ire**
Closes #29

### CODE REVIEW

**Comment by goetas** [comment]
Is there a reason for trimming only specific characters instead of using the default php setting to trim any whitespace chr by default?

**Comment by greg0ire** [comment]
I'm going to try with no arguments but I saw that `\n` is in the list.

**Comment by greg0ire** [comment]
It works when I remove the argument from most calls, but not all… what should I do?

**Comment by goetas** [comment]
I'm fine with the current code, was just curious about it. 
Feel free to choose the option you prefer.

**Pull request merged**
