### PR TITLE
Move initialization to the constructor

### PR DESCRIPTION
**Pull request by greg0ire**
Since this class no longer use statism, we have state and we can
initialize it in the constructor.

### CODE REVIEW

**Comment by goetas** [comment]
I think you forgot to add the call in the constructor... am I right?

**Comment by greg0ire** [comment]
No, it's just the diff that is confusing. I move the entirety of `init()` into the constructor

**Comment by goetas** [comment]
Then there is a small bug. `if ($highlighter === null) { ... return;` will skip initialization

**Comment by greg0ire** [comment]
Oh right! Good thing we have reviews :sweat_smile:

**Pull request merged**
